[project]
name = "flaskr"
version = "1.0.0"
authors = [
    { name="Steven Crouse" },
]
description = "A basic blog app built with the Flask tutorial."
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"